const majors = ['愚人','魔术师','女祭司','皇后','皇帝','教皇','恋人','战车','力量','隐者','命运之轮','正义','倒吊人','死神','节制','恶魔','高塔','星星','月亮','太阳','审判','世界']
const suits = [['权杖','火'],['圣杯','水'],['宝剑','风'],['星币','土']]
const minorRanks = ['王牌','二','三','四','五','六','七','八','九','十','侍者','骑士','王后','国王']
const topics = { love:'关系与感情', career:'工作与方向', growth:'自我成长', decision:'选择与决定', open:'开放探索' }
const questionOptions = {
  love:['我在这段关系中最需要看清什么？','我该如何更诚实地表达自己的需要？','这段关系正在教会我什么？'],
  career:['我目前的工作方向值得继续投入吗？','我下一步最应该把精力放在哪里？','我该如何面对当前的压力或变化？'],
  growth:['我现在最需要突破的内在卡点是什么？','有什么能力值得我开始培养？','我该怎样更好地照顾自己的状态？'],
  decision:['这个选择中我忽略了什么？','我需要用什么标准做决定？','现在行动与等待，各自意味着什么？'],
  open:['我此刻最需要听见的提醒是什么？','最近有什么主题正在反复出现？','我现在可以从哪里开始？']
}
const majorMeanings = {
  '愚人':'新的旅程、信任直觉、保持开放','魔术师':'资源、行动力、把想法变成现实','女祭司':'直觉、内在声音、暂时观察','皇后':'滋养、创造力、丰盛与成长','皇帝':'秩序、边界、承担责任','教皇':'传统、学习、寻找可靠的指导','恋人':'选择、连接、价值观的一致','战车':'意志、推进、掌握方向','力量':'耐心、柔韧、温和而坚定','隐者':'独处、反思、寻找自己的答案','命运之轮':'转机、周期、顺势而为','正义':'平衡、事实、承担选择的结果','倒吊人':'暂停、换个角度、放下控制','死神':'结束、转化、为新阶段腾出空间','节制':'调和、节奏、找到中间道路','恶魔':'执着、诱惑、看见束缚','高塔':'突然变化、旧结构松动、真实浮现','星星':'希望、疗愈、重新相信未来','月亮':'不确定、情绪、分辨恐惧与直觉','太阳':'清晰、活力、坦诚的喜悦','审判':'觉醒、复盘、回应内心召唤','世界':'完成、整合、进入下一阶段'
}
const cards = [...majors.map((name,i)=>({id:`major-${i}`,name,kind:'大阿卡纳',meaning:majorMeanings[name]})), ...suits.flatMap(([suit,element])=>minorRanks.map((rank,i)=>({id:`${suit}-${i}`,name:`${suit}${rank}`,kind:`${suit} · ${element}`,meaning:`${suit}的${rank}提示你关注${suit==='权杖'?'行动与意志':suit==='圣杯'?'感受与连接':suit==='宝剑'?'思考与沟通':'现实资源与节奏'}`})))]
const reversed = '这股能量目前有些受阻或失衡。先放慢一步，看看你是否正在逃避一个需要被看见的事实。'
const positions = ['过去带来的影响','现在正在发生什么','未来可以怎样展开']
const state = { mode:'home', topic:'open', question:'', spread:'three', drawn:[], revealed:0, muted:true, dailyCard:null, dailyRevealed:false }
const app = document.querySelector('#app')

function tone(freq=440,duration=.12){if(state.muted)return;const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;const ctx=new Ctx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=freq;osc.type='sine';gain.gain.setValueAtTime(.04,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration)}
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function hash(value){let n=2166136261;for(const c of value)n=(n^c.charCodeAt(0))*16777619;return Math.abs(n>>>0)}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function todayText(){return new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date())}
function dailyCard(){const key=todayKey(),base=cards[hash(key)%cards.length];return {...base,orientation:hash(`${key}-orientation`)%10<3?'reversed':'upright'}}
function shell(content){app.innerHTML=`<main class="shell"><header><button class="brand" data-home>✦ 月隐 <span>Tarot</span></button><button class="sound" data-sound>${state.muted?'声音已关闭':'声音已开启'}</button></header>${content}<footer>仅用于娱乐与自我探索 · 把问题交给牌，把答案留给自己</footer></main>`;bind()}
function home(){state.mode='home';shell(`<section class="hero"><div class="eyebrow">A QUIET MOMENT WITH YOURSELF</div><h1>把问题交给牌<br><em>把答案留给自己</em></h1><p>一次安静、私密、可回看的塔罗自我探索。</p><div class="hero-card"><div class="orb">☾</div><div class="card-caption">THE MOON VEIL</div></div><div class="entry-grid"><button class="entry primary" data-start><span class="entry-kicker">QUESTION READING</span><strong>开始抽牌 <b>→</b></strong><small>针对一个具体问题，选主题、选牌阵，再让三张牌展开线索。</small></button><button class="entry secondary" data-daily><span class="entry-kicker">DAILY GUIDANCE</span><strong>今日一牌 <b>→</b></strong><small>不需要提问；每天固定一张牌，给你一个关键词和可执行提醒。</small></button></div></section>`)}
function customSetup(){state.mode='custom';const chips=questionOptions[state.topic];shell(`<section class="panel journey"><div class="steps"><span class="active">1 主题</span><i>·</i><span class="active">2 问题</span><i>·</i><span>3 抽牌</span></div><div class="eyebrow">QUESTION READING</div><h2>先说清楚你想看什么</h2><p class="muted">问题越具体，牌阵越容易成为有用的自我反思工具。</p><div class="topic-grid">${Object.entries(topics).map(([id,label])=>`<button class="topic-option ${state.topic===id?'selected':''}" data-topic="${id}">${label}</button>`).join('')}</div><label>选择一个问题，或自己写下问题 <span>可选</span><textarea id="question" maxlength="120" placeholder="例如：我最近最需要关注什么？">${escapeHtml(state.question)}</textarea></label><div class="question-chips">${chips.map(q=>`<button class="chip" data-question="${escapeHtml(q)}">${q}</button>`).join('')}</div><div class="spread-preview"><div><span class="eyebrow">SPREAD</span><strong>过去 · 现在 · 未来</strong><small>三张牌分别看见背景、当下与下一步。</small></div><span class="spread-count">3<br><small>张牌</small></span></div><button class="primary wide" data-draw>开始洗牌并抽取三张牌 <span>→</span></button><button class="link" data-home>返回首页</button></section>`)}
function cardMarkup(card,index,position){return `<article class="draw-card ${index<state.revealed?'revealed':''}" data-reveal="${index}"><div class="face"><div class="card-number">${String(index+1).padStart(2,'0')}</div><div class="glyph">${card.name.length>3?'✧':'☾'}</div><h3>${card.name}</h3><small>${card.kind}</small><div class="orientation">${card.orientation==='upright'?'正位':'逆位'}</div><div class="position-label">${position}</div></div><div class="back"><div class="back-orb">✦</div><span>点击翻牌</span></div></article>`}
function customReading(){const question=state.question||'我现在最需要看清什么？';shell(`<section class="reading"><div class="reading-top"><div><div class="eyebrow">QUESTION READING · ${topics[state.topic]}</div><h2>让三张牌回答你的问题</h2><p class="muted">问题：${escapeHtml(question)}</p></div><button class="secondary small" data-new>重新开始</button></div><div class="spread three">${state.drawn.map((card,i)=>cardMarkup(card,i,positions[i]))}</div>${state.revealed===3?interpretation(question):'<p class="hint">按顺序翻开三张牌，先看见，再解释。</p>'}</section>`)}
function interpretation(question){const [a,b,c]=state.drawn;const item=(card,pos)=>`<div class="meaning"><strong>${pos} · ${card.name}（${card.orientation==='upright'?'正位':'逆位'}）</strong><p>${card.orientation==='upright'?card.meaning:reversed}</p><small>结合你的问题：${escapeHtml(question)}，这里更值得观察的是：${card.orientation==='upright'?'你如何把这股能量转化为一个具体选择。':'你在哪里把注意力交给了恐惧、惯性或他人的期待。'}</small></div>`;return `<div class="interpretation"><div class="eyebrow">A CLEARER REFLECTION</div><h3>牌面给出的三层线索</h3>${item(a,'过去带来的影响')}${item(b,'现在的核心状态')}${item(c,'未来的行动方向')}<div class="synthesis"><strong>整体关系</strong><p>${a.name}带来的背景正在影响${b.name}所代表的当下，而${c.name}提醒你不要只停留在理解上。三张牌放在一起，更像是一条从“看见”走向“选择”的路径。</p></div><div class="advice"><strong>今天可以做的一件事</strong><p>把问题改写成一个你能控制的动作，并在今天为它安排一个明确的时间。</p></div><p class="disclaimer">这是一种自我探索式解读，不是确定性预言，也不能替代医疗、法律或财务专业意见。</p></div>`}
function dailyIntro(){state.mode='daily';state.dailyCard=dailyCard();state.dailyRevealed=false;shell(`<section class="daily-page"><div class="eyebrow">DAILY GUIDANCE</div><div class="daily-date">${todayText()}</div><h2>今天，给自己一个方向</h2><p class="muted">今日牌每天只变化一次。你可以在一天中任何时候回来，再次看见同一张牌。</p><div class="daily-card-wrap"><div class="daily-card ${state.dailyRevealed?'is-revealed':''}"><div class="daily-face"><div class="glyph">${state.dailyCard.name.length>3?'✧':'☾'}</div><h3>${state.dailyCard.name}</h3><small>${state.dailyCard.kind}</small><span>${state.dailyCard.orientation==='upright'?'正位':'逆位'}</span></div><div class="daily-back"><div class="back-orb">✦</div><small>今天的牌</small></div></div></div>${state.dailyRevealed?dailyResult():'<button class="primary" data-daily-reveal>翻开今日的牌 <span>→</span></button>'}<button class="link" data-home>返回首页</button></section>`)}
function dailyResult(){const c=state.dailyCard;const positive=c.orientation==='upright';return `<div class="daily-result"><div class="eyebrow">TODAY'S REFLECTION</div><h3>${positive?'今日关键词：把注意力放回当下':'今日关键词：先调整节奏'}</h3><p>${positive?c.meaning:reversed}</p><div class="daily-columns"><div><strong>今日提醒</strong><span>${positive?'不要只等待更好的时机，先完成一个小动作。':'不必急着证明自己，先确认你真正想要的是什么。'}</span></div><div><strong>今日行动</strong><span>${positive?'用十分钟处理一件被拖延的小事。':'给自己留出一段不被打扰的时间，写下三件可控的事。'}</span></div></div><p class="disclaimer">今日一牌是当天的自我提醒，不是对未来的确定性预测。</p></div>`}
function bind(){document.querySelectorAll('[data-home]').forEach(b=>b.onclick=home);document.querySelector('[data-start]')?.addEventListener('click',customSetup);document.querySelector('[data-daily]')?.addEventListener('click',dailyIntro);document.querySelector('[data-sound]')?.addEventListener('click',e=>{state.muted=!state.muted;e.currentTarget.textContent=state.muted?'声音已关闭':'声音已开启';tone(660)});document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;customSetup()});document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{state.question=b.dataset.question;customSetup()});document.querySelector('#question')?.addEventListener('input',e=>{state.question=e.target.value});document.querySelector('[data-draw]')?.addEventListener('click',()=>{state.question=document.querySelector('#question').value.trim()||'我现在最需要看清什么？';state.drawn=shuffle(cards).slice(0,3).map(c=>({...c,orientation:Math.random()<.28?'reversed':'upright'}));state.revealed=0;tone(220,.2);customReading()});document.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.reveal);if(i===state.revealed){state.revealed++;tone(440+i*100,.18);customReading()}});document.querySelector('[data-new]')?.addEventListener('click',customSetup);document.querySelector('[data-daily-reveal]')?.addEventListener('click',()=>{state.dailyRevealed=true;tone(520,.2);dailyIntro()})}

const renderDaily= dailyIntro
dailyIntro=function(){const wasDaily=state.mode==='daily';renderDaily();if(wasDaily){state.dailyRevealed=true;document.querySelector('.daily-card')?.classList.add('is-revealed');const button=document.querySelector('[data-daily-reveal]');if(button)button.outerHTML=dailyResult()}}
home()
